# Generated by Django 2.1.1 on 2018-11-21 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Mr. ', max_length=60)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('qty', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2018, 11, 21, 21, 29, 15, 944833, tzinfo=utc))),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered')], max_length=20)),
                ('sale_by', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
        ),
    ]
